### ISSUE TITLE
Example needed to use the MVCBootstrap class

### ISSUE THREAD

**Issue by sidorg222** [JellyMaster/MVCBootstrap#1]
I would appreciate an example, on how to use your MVCBoostrap validation summary class.  It looks exactly like what I need, but haven't been able to completely figure it out.

Thanks,
George

**Comment by JellyMaster** [comment]
Hi George, 

You can take a look at the wiki for further details here: https://github.com/JellyMaster/MVCBootstrap/wiki/BootStrapped-Validation-Summary

But as a simple overview here is a basic configuration that can be set up to change the validation from it's default setup: 

```
     @Html.BootStrapValidationSummary(new BootStrapExtensions.BootstrapValidationSummaryOptions()
 {

ShowModelErrors = true //Show attached model errors that have validation
,
Title = "Help! Something has gone wrong" //lead title for the panel
,
DisplayMode = ErrorMode.ClosableAlert //change the display mode from Alert to closable alert
,
IntroductionBlock = "Some sample text to display as an introduction piece" //changing the default text displayed in the intro block.



    })
```

Here is a sample image that I have created for you: 
![bootstrap val image](https://cloud.githubusercontent.com/assets/4993772/3095082/33fbc48c-e5c3-11e3-9f83-3c416188e716.png)

To get the error message onto the screen I simply added an error to the model state like so: 

```
     [HttpPost]
           public ActionResult Index(string value)
    {

        ModelState.AddModelError("", "There is an error being attached to this screen");


        return View(ModelState);
    }
```

Hope this helps. 

I have left out styling for now as this should be explained in the wiki section I linked to. 

Any comments/ improvements will be gratefully received.
