### ISSUE TITLE
Successful Modal Popup Messaj Dynamic

### ISSUE THREAD

**Issue by murattdogan** [JellyMaster/MVCBootstrap#5]
Hi, I work as long as successful dynamic Modal Popup, error messages, etc. MVC I want to give information at the end is a kind of work done, but I did not succeed. I need your help I just started my new MVC yazılımcılıkta from .Siz counted as a message if you want an example of this dynamic, I'm glad. I already thank. I also nuget also apply if you want your application gives an error, you will see hatayu run after your own pc download

**Comment by JellyMaster** [comment]
I'm sorry. I am not quite understanding your request. 

Are you asking for a successful "pop up" message after some task is completed? 

If you are then this is not how this control was created. It was created to replace the existing validation summary control that Microsoft included within the MVC framework. 

I would suggest you maybe look at this is as a possible solution if this is what you are after. 

http://demos.telerik.com/kendo-ui/notification/index

Telerik has built a number of controls that are open source for the most part (some of their more complex controls require a paid for license but a large number of their controls from the kendo suite are open sourced) that will help enhance your site. I have been using their control suites for a few years now. There are other alternatives to this as well. The same functionality could be built using standard html/javascript. 

As for the build errors I will look into them as part of the other issue you raised.
